import { Inter, Noto_Sans_Lao } from "next/font/google";
import "./globals.css";

// Components
import { Providers } from "./providers";
import { Header, Footer } from "@/components";

// const inter = Inter({ subsets: ["latin"] });
const notoSansLao = Noto_Sans_Lao({ subsets: ["lao"] });

export const metadata = {
  title: "ເວັບໄຊທ໌ຂ່າວສານ ພະແນກກະສິກຳປ່າໄມ້ແຂວງສະຫວັນນະເຂດ",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={notoSansLao.className}>
        <Providers>
          <Header />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
